services:
  - type: web
    name: coldemail-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && cd ../client && npm install && npm run build && cd ../server
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://real-mailing.onrender.com
      - key: VITE_API_URL
        value: https://real-mailing.onrender.com
  - type: static_site
    name: coldemail-client
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://coldemail-server.onrender.com

